{% set version = "2.4.0" %}

package:
  name: conda-smithy
  version: {{ version }}

source:
  url: https://github.com/conda-forge/conda-smithy/archive/v{{ version }}.tar.gz
  sha256: a853196d4c934c73851b914bf40c174e76147ee2167dd662845df486a6247f84

build:
  number: 0
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
    - rm -f "${PREFIX}/bin/conda"           # [not win]
    - del /f /q "%PREFIX%\\Scripts\\conda"  # [win]
  entry_points:
    - feedstocks = conda_smithy.feedstocks:main
    - conda-smithy = conda_smithy.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - conda-build-all >=1.0.3
    - conda
    - conda-build >=1.21.12,!=2.0.9
    - jinja2
    - requests
    - pycrypto
    - gitpython
    - pygithub <2
    - ruamel.yaml

test:
  imports:
    - conda_smithy
    - conda_smithy.ci_register
    - conda_smithy.configure_feedstock
  commands:
    - conda smithy --help

about:
  home: https://github.com/conda-forge/conda-smithy
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: The tool for managing conda-forge feedstocks

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
