{% set version = "2.4.5" %}

package:
  name: conda-smithy
  version: {{ version }}

source:
  url: https://github.com/conda-forge/conda-smithy/releases/download/v{{ version }}/conda-smithy-{{ version }}.tar.gz
  sha256: b6e8e93de0240278d9cf2edd10bb972c5063e6f4653ecc9335f7db6b4ecfc65d

build:
  number: 1
  noarch: python
  script:
    - python setup.py install --single-version-externally-managed --record=record.txt
    - rm -f "${PREFIX}/bin/conda"           # [not win]
    - del /f /q "%PREFIX%\\Scripts\\conda"  # [win]
  entry_points:
    - feedstocks = conda_smithy.feedstocks:main
    - conda-smithy = conda_smithy.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - conda-build-all >=1.1.1
    - conda <4.4
    - conda-build 2.1.*
    - jinja2
    - requests
    - pycrypto
    - gitpython
    - pygithub <2
    - ruamel.yaml

test:
  imports:
    - conda_smithy
    - conda_smithy.ci_register
    - conda_smithy.configure_feedstock
  commands:
    - conda smithy --help
    - py.test
  files:
    - tests/*
  requires:
    - pytest


about:
  home: https://github.com/conda-forge/conda-smithy
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: The tool for managing conda-forge feedstocks

extra:
  recipe-maintainers:
    - jakirkham
    - pelson
    - ocefpaf
    - isuruf
