{% set version = "0.10.0" %}

package:
  name: conda-smithy
  version: {{ version }}

source:
  fn: conda-smithy-v{{ version }}.tar.gz
  url: https://github.com/conda-forge/conda-smithy/archive/v{{ version }}.tar.gz
  sha256: 8e535c225c9552f13d5dd3de4bd83d819a3b17329fb52b201625e5db9ff87d80

build:
    number: 0
    script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - setuptools
    - conda-build-all
    - conda
    - conda-build
    - jinja2
    - requests
    - pycrypto
    - gitpython
    - pygithub <2
    - ruamel.yaml

test:
    imports:
        - conda_smithy
        - conda_smithy.ci_register
        - conda_smithy.configure_feedstock
    commands:
        - conda smithy --help

about:
    home: https://github.com/conda-forge/conda-smithy
    license: BSD 3-clause
    summary: The tool for managing conda-forge feedstocks

extra:
    recipe-maintainers:
        - pelson
